version: '2'
services:
  tws:
    image: ib-gateway:latest
    ports:
      - 4001:4001
      - 4002:4002
      - 5900:5900
    volumes:
      - ./ib/IBController.ini:/root/IBController/IBController.ini
      - ./ib/jts.ini:/root/Jts/jts.ini
    environment:
      - TZ=Asia/Hong_Kong
      # Variables pulled from /IBController/IBControllerGatewayStart.sh
      - VNC_PASSWORD=1234 # CHANGEME
      - TWS_MAJOR_VRSN=981
      - IBC_INI=/root/IBController/IBController.ini
      - IBC_PATH=/opt/IBController
      # - TWS_PATH=/root/Jts
      # - TWS_CONFIG_PATH=/root/Jts
      # - LOG_PATH=/opt/IBController/Logs
      # - JAVA_PATH=/opt/i4j_jres/1.8.0_152/bin # JRE is bundled starting with TWS 952
      - TRADING_MODE=paper # either paper or live
      # - TWSUSERID= # IB account
      # - TWSPASSWORD= # IB account password
      # - FIXUSERID=
      # - FIXPASSWORD=
      - APP=GATEWAY