version: '3'
services:
  tws:
    image: ib-gateway:latest
    ports:
      - 4001:4001
      - 4002:4002
      - 5900:5900
    volumes:
      - ./ib/IBController.ini:/root/IBController/IBController.ini
      - ./ib/jts.ini:/root/Jts/jts.ini
      - ./Logs:/opt/IBController/Logs
      - ./Settings:/opt/IBController/Settings
    environment:
      - TZ=Asia/Hong_Kong
      - VNC_PASSWORD=1234 # CHANGEME
      # Variables pulled from /IBController/IBControllerGatewayStart.sh
      - TWS_MAJOR_VRSN=981
      - IBC_INI=/root/IBController/IBController.ini
      - TRADING_MODE=paper
      - TWOFA_TIMEOUT_ACTION=exit
      - IBC_PATH=/opt/IBController
      - TWS_PATH=/root/Jts
      - TWS_SETTINGS_PATH=/opt/IBController/Settings
      - LOG_PATH=/opt/IBController/Logs
      - TWSUSERID= # IB account
      - TWSPASSWORD= # IB account password
      - FIXUSERID=
      - FIXPASSWORD=
      - JAVA_PATH=/opt/i4j_jres/1.8.0_152-tzdata2019c/bin # JRE is bundled starting with TWS 952
      - HIDE=
      - APP=GATEWAY
